language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
  - ruby-head

env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
    - env: "RAILS_VERSION=master"
